name: angadi
description: A new Flutter application.

publish_to: 'none'


version: 1.0.0+25

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  firebase_auth: ^0.16.1
  apple_sign_in: ^0.1.0
  carousel_slider: ^1.4.1
  flutter_svg: ^0.17.1
  firebase_storage: ^3.1.6
  shared_preferences: ^0.5.12
  fancy_shimmer_image: ^1.2.0
  google_fonts: ^0.3.10
  webview_flutter: ^1.0.7
  fluttertoast: ^7.1.1
  flutter_open_whatsapp: ^0.1.2
  flutter_paytabs_bridge_emulator: ^1.0.1-beta
  cached_network_image: ^2.3.3
  persistent_bottom_nav_bar: ^2.1.0
#  intl: ^0.16.1
  progress_dialog: ^1.2.4
  expandable: ^4.1.4
  getwidget: ^1.1.0
  getflutter: ^1.0.11
  image_picker: ^0.6.7+3
  cloud_firestore: ^0.13.7
  place_picker: ^0.9.15
  auto_route: ^0.3.1
  sqflite: ^1.3.1
  animations: ^1.0.0+5
  flutter_rating_bar: ^3.0.1+1
  flutter_automation: ^1.1.4
  geolocator: ^5.1.3
  back_button_interceptor: ^2.0.2
  flutter_dropdown: ^0.0.8
  geocoder: ^0.2.1
  google_map_location_picker: ^3.0.0
  google_maps_flutter: ^0.5.21+12
  url_launcher: ^5.7.5
  timeline_tile: ^1.0.0
  google_sign_in: ^4.5.9
  flutter_polyline_points: ^0.2.4
  lottie: ^0.6.0
  string_similarity: ^1.1.0

#  flutter_paytabs_sdk: ^1.0.0
  path_provider: ^1.6.11
  location: ^2.3.5
  firebase_messaging: ^6.0.16
  flutter_feather_icons: ^1.0.3
  font_awesome_flutter: ^8.10.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  auto_route_generator: ^0.3.2



flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/animations/


  fonts:
    - family: Josefin Sans
      fonts:
        - asset: assets/fonts/.15510.ttf
        - asset: assets/fonts/.15498.ttf
          weight: 700

    - family: Roboto
      fonts:
        - asset: assets/fonts/.15510.ttf
        - asset: assets/fonts/.15498.ttf
          weight: 700
    - family: .AppleSystemUIFont8
      fonts:
        - asset: assets/fonts/SFNS.ttf